Layout and nav updates
TehcCringe/TehcCringe pull request #43
Opened 2024-11-30 13:54 UTC by ChristianPavilonis

- **adjusts alignment for main content**
- **Spaces footer away from content darkens the border color**

2024-11-30 13:55 UTC, ChristianPavilonis commented
Maybe we should include a CTA in the Nav for submitting an article.

It would just link to the readme I guess.

2024-11-30 20:55 UTC, IroncladDev commented
You are allowed to be absolutely unhinged with your commit messages, btw

2024-11-30 21:02 UTC, IroncladDev requested changes
Some changes

I apologize at how nit-picky I am about clean JSX

2024-11-30 21:02 UTC, IroncladDev commented on app/layout.tsx
> +        <header className="max-w-[1280px] w-full mx-auto px-4 pt-8 flex items-center justify-between pb-8">
Try to use the `styled()` util from `react-tailwind-variants` for long classes like this

```tsx
const Header = styled("header", {
  base: "max-w-[1280px] w-full mx-auto px-4 pt-8 flex items-center justify-between pb-8"
});
```

You can also do

```tsx
<Flex className="max-w-[1280px] !pl-0" p={8} center width="full" asChild>
  <header>...</header>
</Flex>
```

2024-11-30 21:02 UTC, IroncladDev commented on tailwind.config.ts
> +        primary: "#ba43f7"
Let's use the `mauve` color in the [catppuccin](https://github.com/catppuccin/catppuccin) palette

2024-12-01 14:05 UTC, ChristianPavilonis commented on app/components/logo-mark.tsx
> +export default function LogoMark(props: {className?: string}) {
I did this, but I needed a [build dep](https://github.com/TehcCringe/TehcCringe/pull/43/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R33) to inline the svg, lmk if that's what you prefer.

img tags don't let us style outside of the svg file itself, so we wouldn't be able to modify the fill color on hover for example.

2024-12-02 14:07 UTC, IroncladDev approved these changes
LGTM

2024-12-02 14:28 UTC, merged